<a href="https://colab.research.google.com/github/JumpLusWu/CIS700/blob/master/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clone Git (0 pts)

Run the following to get the required files needed for this assignment. 

In [1]:
!git clone https://github.com/cis700/hw1-release.git
!mv hw1-release/dills/* .
!mv hw1-release hw1

Cloning into 'hw1-release'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 26 (delta 6), reused 23 (delta 6), pack-reused 0
Unpacking objects: 100% (26/26), done.


# Classical vs. Deep Learning Approach


## Question 1. Using Decision Trees to Classify Fashion-MNIST (10 pts)

**Understanding the Dataset**

The first step to machine learning is to understand the dataset that you're given. Therefore, familiarize yourself with the Fashion-MNIST dataset. We recommend reading the paper published about the dataset, which is detailed [here](https://arxiv.org/pdf/1708.07747.pdf).

**Q1a (2 pts):** Explain at a high level what the dataset is (i.e. what are the specifications of the input data and associated labels).

In [0]:
he input data comes from the pictures of fashion products and is preprocessed to have the same image size as the MINST dataset. It has ten different classes and is labeled using numbers.

**Loading the Data**

Since there's no built in dataloader for Fashion-MNIST built into sci-kit learn, we've created a dataloader that you may use. The first code snippet is to the install [wget](https://pypi.org/project/wget/) and sets up the directory structure for your data to go in.

In the second code snippet, we provide the function made by the authors of the fashion-MNIST dataset to extract the downloaded data.

**Q1b (3 pts):** Fill in the load_datasets function such that it returns the training data, training labels, testing data, and testing labels. In your report, indicate the dimensions of the training set and the testing set respectively. 

In [2]:
!pip install wget
!mkdir -p data/fashion

  Stored in directory: /root/.cache/pip/wheels/40/15/30/7d8f7cea2902b4db79e3fea550d7d7b85ecb27ef992b618f3f
Successfully built wget


In [0]:
import os.path
import wget
import pdb

## Function provided by the creators of Fashion-MNIST to unpack and load their data
def load_mnist(path, kind='train'):
    import os
    import gzip
    import numpy as np

    """Load MNIST data from `path`"""
    labels_path = os.path.join(path,
                               '%s-labels-idx1-ubyte.gz'
                               % kind)
    images_path = os.path.join(path,
                               '%s-images-idx3-ubyte.gz'
                               % kind)

    with gzip.open(labels_path, 'rb') as lbpath:
        labels = np.frombuffer(lbpath.read(), dtype=np.uint8,
                               offset=8)

    with gzip.open(images_path, 'rb') as imgpath:
        images = np.frombuffer(imgpath.read(), dtype=np.uint8,
                               offset=16).reshape(len(labels), 784)

    return images, labels

In [0]:
# Fill in this method to load the Fashion-MNIST dataset
def load_datasets():
  base_URL = "http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/"
  files = ["train-images-idx3-ubyte.gz", "train-labels-idx1-ubyte.gz", "t10k-images-idx3-ubyte.gz", "t10k-labels-idx1-ubyte.gz"]
  fashion_dir = "data/fashion"
  import wget
  base_URL = "http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/"
  files = ["train-images-idx3-ubyte.gz", "train-labels-idx1-ubyte.gz", "t10k-images-idx3-ubyte.gz", "t10k-labels-idx1-ubyte.gz"]
  for i in range(4):
    wget.download(base_URL+files[i], 'data/fashion') # download the compressed data file
  train_images, train_labels =load_mnist('data/fashion', kind='train')
  test_images, test_labels=  load_mnist('data/fashion', kind='t10k')
  # Return the correct four variables
  return train_images, train_labels, test_images, test_labels

train_images, train_labels, test_images, test_labels = load_datasets()

In [7]:
print(train_images
     )

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


**Creating a Classical Classifier**

**Q1c (5 pts):** Use logistic regression to classify the Fashion-MNIST dataset. Note that because this is not sped up by a GPU this may take a few minutes to run. In your report, plot the learning curve for train and validation accuracy and report the final classification accuracy.



## Question 2. Using Deep Learning to Classify Fashion-MNIST (10 pts)

In this section you will also classify the Fashion-MNIST dataset, however, with a deep neural network instead.

**Downloading PyTorch**

Run the code snippet below to install PyTorch / required packages and set up the GPU.

In [0]:
## Required packages
!pip install tensorflow
!pip install scipy
!pip install numpy
!pip install Pillow
!pip install image

## Add any other packages you may need below

In [0]:
# http://pytorch.org/
from os.path import exists
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'
!pip3 install https://download.pytorch.org/whl/cu100/torch-1.0.1-cp36-cp36m-linux_x86_64.whl
!pip3 install torchvision
  
import torch
device =  torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

**PyTorch Tensorboard Integration**

In this class we present the option of using tensorboard to visualize loss / accuracy plots and images. You may choose to use matplotlib instead, however, we recommend using tensorboard as it's becoming the industry standard for analyzing / debugging neural networks. 

Simply run the code snippets below in the order provided, and click on the link to open up the tensorboard dashboard (which should be blank right now!).

In [0]:
LOG_DIR = './logs'
get_ipython().system_raw(
    'tensorboard --logdir {} --host 0.0.0.0 --port 6006 &'
    .format(LOG_DIR)
)

!if [ -f ngrok ] ; then echo "Ngrok already installed" ; else wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip > /dev/null 2>&1 && unzip ngrok-stable-linux-amd64.zip > /dev/null 2>&1 ; fi

In [0]:
get_ipython().system_raw('./ngrok http 6006 &')

In [0]:
! curl -s http://localhost:4040/api/tunnels | python3 -c \
    "import sys, json; print('Tensorboard Link: ' +str(json.load(sys.stdin)['tunnels'][0]['public_url']))"

To see how to use Pytorch with tensorboard, check out [this](https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/04-utils/tensorboard/main.py) github repo (specifically in main.py). Try plotting something using tensorboard to ensure that it's all working. For help, come to office hours or check out [this](https://stackoverflow.com/questions/47818822/can-i-use-tensorboard-with-google-colab) link (where we got the tensorboard-colab integration).

**Important:** Note that we've changed the logging folder to "./logs" . Keep that in mind when using tensorboard.

**PyTorch Dataloaders **

The first step to deep learning is to create a dataloader. It's important to understand how a dataloader works so you can create a custom dataloader for datasets in the future. To understand more, we highly recommend PyTorch's tutorial on dataloaders detailed [here](https://pytorch.org/tutorials/beginner/data_loading_tutorial.html).

**Q2a (2 pts):** Create a training and testing dataloader for the Fashion-MNIST dataset. Report the size of the training and testing sets respectively (it should match those from the previous question.)

*Hint:* Fashion-MNIST is a highly used dataset, therefore you do not have to create a whole dataloader from scratch. For some help, take a look at Torch's [dataset](https://pytorch.org/docs/stable/torchvision/datasets.html) and [dataloader](https://pytorch.org/docs/stable/data.html) page.

**Creating the Neural Network Model**

PyTorch has a fantastic tutorial on creating a neural network model, detailed [here](https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html).

**Q2b (2 pts):** Using knowledge from lecture and the tutorial from the link above, create a neural network model to classify the Fashion-MNIST dataset. In your report, detail your network architecture, explaining the choices that you made (i.e. depth of the neural network, activation functions, etc).

*NOTE:* You may **not** use convolutional layers in this model.

**Creating the Training Loop**

**Q2c (2 pts):** Create a training loop that goes over the entire Fashion-MNIST dataset once. You should tune all hyperparameters (i.e. batch-size, learning rate, etc). Use tensorboard so that in one graph, plot accuracy vs iterations, and in the other plot loss vs iterations (axis labels are not needed if you're using tensorboard). Report the final testing accuracy and loss.

In [0]:
# Use this object to help with tensorboard integration!
from hw1.helper import Logger
logger = Logger('./logs')

**Q2d (2 pts):** Create a testing loop that outputs the accuracy of your trained neural network on the test set. Report the evaluation accuracy of your network on this testing set.

*Hint:* Look at the torch.no_grad() function to evaluate your neural network without updating the weights.

**Q2e (2 pts):** Compare the testing accuracy of your neural network vs. the decision tree clasifier you made in the previous part.

# Question 3. Deep Learning Diagnosis

### Q3.1.a MNIST control group (10 pts)

Using the same PyTorch approach as above, tune the hyperparameters for a neural net on the MNIST dataset.  Plot the learning curve and report its final accuracy in your writeup.  This neural net's performance will serve as the reference point (a "control group") for your analysis in parts 3.2, 3.4, and 3.7

In [0]:
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms


# Tune hyperparameters here
num_epochs = 5

# Load the MNIST dataset (images and labels, both train and test) into 2 DataLoaders
train_dataset = torchvision.datasets.MNIST(root='./data_mnist', 
                                           train=True, 
                                           transform=transforms.ToTensor(),
                                           download=True)

test_dataset = torchvision.datasets.MNIST(root='./data_mnist', 
                                          train=False, 
                                          transform=transforms.ToTensor())

class Net(nn.Module):

    def __init__(self):
      # TODO: construct the submodules
      return

    def forward(self, x):
      # TODO: define the forward pass
      return
      
# TODO: complete the train loop
total_step = len(train_dataset)
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_dataset):
      pass
    
# TODO: complete the test loop

# TODO: plot the learning curve.

### Q3.1.b CIFAR control group (10 pts)

Similar to the previous part, create a neural network, training, and testing loop and tune the hyperparameters for the CIFAR-10 dataset. Plot the learning curve and report its final accuracy in your writeup.  This neural net's performance will serve as the reference point (a "control group") for your analysis in parts 3.3, 3.5, and 3.6

In [0]:
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms


# Tune hyperparameters here
num_epochs = 5

# Load the MNIST dataset (images and labels, both train and test) into 2 DataLoaders
train_dataset = torchvision.datasets.CIFAR10(root='./data_cifar', 
                                           train=True, 
                                           transform=transforms.ToTensor(),
                                           download=True)

test_dataset = torchvision.datasets.CIFAR10(root='./data_cifar', 
                                          train=False, 
                                          transform=transforms.ToTensor())

class Net(nn.Module):

    def __init__(self):
      # TODO: construct the submodules
      return

    def forward(self, x):
      # TODO: define the forward pass
      return
      
# TODO: complete the train loop
total_step = len(train_dataset)
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_dataset):
      pass
    
# TODO: complete the test loop

# TODO: plot the learning curve.

For each question below, we will provide 3 PyTorch objects: a DataLoader, a neural network model, and an optimizer (you will load them using dill, a serialization library in Python).  For each question, please complete the following:

a.   Train the given neural net using the given DataLoader and the given optimizer.  Plot the learning curve of the network and report the final accuracy in your writeup.

b.   Identify whether the neural net seems to be training correctly.  If not, debug the issue (e.g. printing parameters, gradients, outputs) and report your methodology in your writeup. In addition, we highly recommend checking out [this](https://docs.google.com/document/d/11R5IiLMjddIWM2csfjFBZ__Adu0sY0zuVhbS3_5lLBQ/edit?usp=sharing) google doc with information about common failure modes for training deep neural networks.

c.   If you identify an issue with any of the 3 given objects, replace the buggy object with one of your own making.  Then retrain the neural net, plot the new learning curve, and report the improved accuracy in your writeup.  Note that in each of the following problems, exactly 1 object out of the DataLoader, the neural net, and the optimizer will be buggy.  You should not have to replace more than 1.

Run the code snippet below for some necessary packages / setup.

In [0]:
import torch
import dill
import torch.optim as optim
device =  torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

### Q3.2 MNIST diagnosis 1 (10 pts)

In [0]:
q_3_2_data_loader = dill.load( open( "q3_2_loader.p", "rb" ) )
train_loader, test_loader = q_3_2_data_loader()
q_3_2_net_loader = dill.load( open( "q3_2_net.p", "rb" ) )
net, optimizer = q_3_2_net_loader()

### Q3.3 CIFAR diagnosis 1 (10 pts)

In [0]:
q_3_3_data_loader = dill.load( open( "q3_3_loader.p", "rb" ) )
train_loader, test_loader = q_3_3_data_loader()
q_3_3_net_loader = dill.load( open( "q3_3_net.p", "rb" ) )
net, optimizer = q_3_3_net_loader()

### Q3.4 MNIST diagnosis 2 (10 pts)

*Hint:* Look at the test accuracy

# New Section

In [0]:
q_3_4_data_loader = dill.load( open( "q3_4_loader.p", "rb" ) )
train_loader, test_loader = q_3_4_data_loader()
q_3_4_net_loader = dill.load( open( "q3_4_net.p", "rb" ) )
net, optimizer = q_3_4_net_loader()

### Q3.5 CIFAR diagnosis 2 (10 pts)

In [0]:
q_3_5_data_loader = dill.load( open( "q3_5_loader.p", "rb" ) )
train_loader, test_loader = q_3_5_data_loader()
q_3_5_net_loader = dill.load( open( "q3_5_net.p", "rb" ) )
net,optimizer = q_3_5_net_loader()

### Q3.6 CIFAR diagnosis 3 (10 pts)

In [0]:
q_3_6_data_loader = dill.load( open( "q3_6_loader.p", "rb" ) )
train_loader, test_loader = q_3_6_data_loader()
q_3_6_net_loader = dill.load( open( "q3_6_net.p", "rb" ) )
net, optimizer = q_3_6_net_loader()

### Q 3.7 MNIST diagnosis 3 (10 pts)

In [0]:
q_3_7_data_loader = dill.load( open( "q3_7_loader.p", "rb" ) )
train_loader, test_loader = q_3_7_data_loader()
q_3_7_net_loader = dill.load( open( "q3_7_net.p", "rb" ) )
net, optimizer = q_3_7_net_loader()